services:
  db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=testdb'
      - 'MYSQL_ROOT_PASSWORD=secret'
    ports:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  backend:
    image: 'mnp:0.0.1-SNAPSHOT'
    ports: 
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
